language: node_js
node_js:
  - "8"
  - "9"
  - "10"
services:
  - mysql
before_install:
  - sudo mysql < ./packages/sandbox-core/test/fixtures/sql/initDB.sql 2>&1
install:
  - npm i
  - npm i codecov
before_script:
  - npm run bootstrap
  - npm run build
script:
  - npm run cov
after_script:
  - codecov
